<?php
/*!
 * http://www.ubertheme.com/
 * Version: 1.0
 * Description: 
 * Author: Uber theme team
 * Author URI: http://www.ubertheme.com/
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
?>

<?php

$listId = uniqid();
$thumbWidth = $config['width'];
$thumbHeight = $config['height'];
$maxChar = $config['max'];

// Calculator with
if ($config['perrow']) {
	$perrow = $config['perrow'];
	$width = 100 / $config['perrow'];
}
// Tablet
$perrowtablet = $config["perrowtablet"];
$widthtablet = 100 / $config["perrowtablet"];
if (isset($config["perrowtabletportrait"]) && $config["perrowtabletportrait"]) {
	$perrowtabletportrait = $config["perrowtabletportrait"];
	$widthtabletportrait = 100 / $config["perrowtabletportrait"];
} else {
	$perrowtabletportrait = $perrowtablet;
	$widthtabletportrait = $widthtablet;
}

// Mobile
$perrowmobile = $config["perrowmobile"];
$widthmobile = 100 / $config["perrowmobile"];
if (isset($config["perrowmobileportrait"]) && $config["perrowmobileportrait"]) {
	$perrowmobileportrait = $config["perrowmobileportrait"];
	$widthmobiletportrait = 100 / $config["perrowmobileportrait"];
} else {
	$perrowmobileportrait = $perrowmobile;
	$widthmobiletportrait = $widthmobile;
}
?>
<style type="text/css">
	#jm_product_grid_<?php echo $listId; ?>.products-grid li.item {
		width: <?php echo $width.'%';?>;
	}

	#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
		clear: both;
	}

	@media only screen and (min-width: 986px) and (max-width: 1235px) {
		#jm_product_grid_<?php echo $listId; ?>.products-grid li.item {
			width: <?php echo $widthtablet.'%';?>;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
			clear: both;
		}
	}

	@media only screen and (min-width: 720px) and (max-width: 985px) {
		#jm_product_grid_<?php echo $listId; ?>.products-grid li.item {
			width: <?php echo $widthtabletportrait.'%';?>;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
			clear: both;
		}
	}

	@media only screen and (max-width: 719px) {
		#jm_product_grid_<?php echo $listId; ?>.products-grid li.item {
			width: <?php echo $widthmobile.'%';?>;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrow;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowtablet;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowtabletportrait;?>n+1) {
			clear: none;
		}

		#jm_product_grid_<?php echo $listId; ?>.products-grid > li:nth-child(<?php echo $perrowmobile;?>n+1) {
			clear: both;
		}
	}

	@media only screen and (max-width: 479px) {
		#jm_product_grid_<?php echo $listId; ?>.products-grid li.item {
			width: <?php echo $widthmobiletportrait.'%';?>;
		}

	<?php if ($perrowmobileportrait == 1):?>
		#jm_product_grid_<?php echo $listId; ?>.products-grid {
			margin: 0;
		}
	<?php endif; ?>
	}
</style>

<script type="text/javascript">
	(function ($) {
		$(document).ready(function () {
			$("#jm_product_grid_<?php echo $listId; ?>").jmproduct({
				qtytable:<?php echo $config['qtytable']; ?>,
				qtytableportrait:<?php echo $config['qtytableportrait']; ?>,
				istable:<?php echo $config['istable']; ?>,
				qtymobile:<?php echo $config['qtymobile']; ?>,
				qtymobileportrait:<?php echo $config['qtymobileportrait']; ?>,
				ismobile:<?php echo $config['ismobile']; ?>
			});
		});
	})(jQuery);
</script>

<!-- List products -->
<div class="jm-product-list <?php echo $config['mode']; ?> clearfix">
	<?php if ($config['title']): ?>
		<div class="page-title category-title">
			<h2><?php echo $config['title']; ?></h2>

			<a title="<?php echo Mage::helper('joomlart_jmproducts')->__('View more'); ?>" class="view-more"
			   href="<?php echo Mage::getModel('core/url')->getUrl('jmproducts/viewall/index', Mage::helper('joomlart_jmproducts')->buildParams($config)); ?>">
				<?php echo Mage::helper('joomlart_jmproducts')->__('View more'); ?>
			</a>
		</div>
	<?php endif; ?>

	<div class="listing-type-grid category-products clearfix">
		<?php
		$collection = $this->getCollection();
		$collectionSize = $collection ? $collection->count() : 0;
		$i = 0;
		?>
		<?php if ($collectionSize): ?>
			<ul id="jm_product_grid_<?php echo $listId; ?>" class="products-grid">
				<?php
				$j = 0;
				$rowCount = ceil($collectionSize / $config['perrow']);
				foreach ($collection->getItems() as $product):
					if ($i % $config['perrow'] == 0) {
						$j++;
					}
					$i++;

					$product = Mage::getModel('catalog/product')->load($product->getId());
                    
                    //get label 
                    if (isset($showLabel) AND $showLabel){
                        $attribute = $product->getResource()->getAttribute('label');
                        if (is_object($attribute)) {
                            $options = $attribute->getSource()->getAllOptions(true, true);
                            foreach ($options as $option) {
                                if ($option['value'] == $product->getData("label")) {
                                    $class = $option['label'];
                                }
                            }
                            $attDefaultValue = $attribute->getDefaultValue();
                            $attributeValue = Mage::getModel('catalog/product')->load($product->getId())->getlabel();
                            $attributeValueName = Mage::getModel('catalog/product')->load($product->getId())->getAttributeText('label');
                            if (strlen($attributeValue) && ($attDefaultValue !== $attributeValue)) {
                                $labelType = $class;
                                $labelName = $attributeValueName;
                            } else {
                                $labelType = "";
                            }
                        }
                    }
					?>
					<li class="item <?php if ($j == $rowCount) : echo "item-row-last"; endif; ?> <?php if (($i - 1) % $config['perrow'] == 0): ?> first<?php elseif ($i % $config['perrow'] == 0): ?> last<?php endif; ?> p-item">
						<div class="inner">
							<!-- Product image -->
							<p class="product-image">
								<a title="<?php echo $this->htmlEscape($product->getName()) ?>"
								   href="<?php echo $product->getProductUrl() ?>">
									<img
										src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize($thumbWidth, $thumbHeight)->setWatermarkSize('30x10'); ?>"
										alt="<?php echo $this->htmlEscape($product->getName()) ?>"/>
								</a>
								<?php if (isset($labelType) AND isset($showLabel) AND $showLabel): ?>
									<span class="<?php echo $labelType; ?>-label label"><?php echo $labelName; ?></span>
								<?php endif; ?>
							</p>

							<!-- Product Description -->
							<div class="product-information">
								<h5 class="product-name">
									<a title="<?php echo $this->htmlEscape($product->getName()) ?>"
									   href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a>
								</h5>
								<?php echo $this->getReviewsSummaryHtml($product, true, true) ?>
								<?php echo $this->getPriceHtml($product, true, '_jmproduct_' . uniqid()); ?>
								<?php
								if ($maxChar) :
									$productDesc = $product->getDescription();
									$productShortDesc = $product->getShortDescription();
								?>
									<p class="pdescription"><?php echo mb_substr(nl2br(strlen($productDesc) > 10 ? $productDesc : $productShortDesc), 0, $maxChar, 'UTF-8') . '...'; ?></p>
								<?php endif; ?>
								<!-- Add to cart -->
								<?php if ($product->isSaleable()): ?>
									<button class="button btn-cart"
											onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')">
										<span><?php echo $this->helper("catalog")->__('Add to Cart'); ?></span>
									</button>
								<?php else: ?>
									<div
										class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock'); ?></div>
								<?php endif; ?>
								<!-- Add to links -->
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li>
											<a href="<?php echo $this->helper('wishlist')->getAddUrl($product); ?>"
											   class="link-wishlist">
												<?php echo $this->__('Wishlist'); ?>
											</a>
										</li>
									<?php endif; ?>
									<?php if ($compareUrl = $this->getAddToCompareUrl($product)): ?>
										<li>
											<a href="<?php echo $compareUrl ?>"
											   class="link-compare"><?php echo $this->__('Compare'); ?></a>
										</li>
									<?php endif; ?>
								</ul>
							</div>
							<!-- /Product information -->
						</div>
					</li>
				<?php endforeach; ?>
			</ul>
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
		<?php else: ?>
			<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php endif; ?>
	</div>
</div>
<div class="clearfix"></div>
<!--// List products -->