<?php
/*!
 * http://www.ubertheme.com/
 * Version: 1.0
 * Description:
 * Author: Uber theme team
 * Author URI: http://www.ubertheme.com/
 *
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
?>

<?php
$collection = $this->getCollection();
$collectionSize = $collection ? $collection->count() : 0;

if ($collectionSize):
	$thumbWidth = $config['width'];
	$thumbHeight = $config['height'];
	$maxChar = $config['max'];

	$i = 0; $j = 0;
	foreach ($collection->getItems() as $product):
		$rowCount = ceil($collectionSize / $config['perrow']);
		if ($i % $config['perrow'] == 0){
			$j++;
		}
		$i++;

		$product = Mage::getModel('catalog/product')->load($product->getId());
		$attribute = $product->getResource()->getAttribute('label');
		if (is_object($attribute)) {
			$options = $attribute->getSource()->getAllOptions(true, true);
			foreach ($options as $option) {
				if ($option['value'] == $product->getData("label")) {
					$class = $option['label'];
				}
			}
			$attDefaultValue = $attribute->getDefaultValue();
			$attributeValue = Mage::getModel('catalog/product')->load($product->getId())->getlabel();
			$attributeValueName = Mage::getModel('catalog/product')->load($product->getId())->getAttributeText('label');
			if (strlen($attributeValue) && ($attDefaultValue !== $attributeValue)) {
				$labelType = $class;
				$labelName = $attributeValueName;
			} else {
				$labelType = "";
			}
		}

		?>
		<li class="item <?php if ($j == $rowCount) : echo "item-row-last"; endif; ?> <?php if (($i - 1) % $config['perrow'] == 0): ?> first<?php elseif ($i % $config['perrow'] == 0): ?> last<?php endif; ?>">
			<div class="inner">
				<!-- Product image -->
				<p class="product-image">
					<a title="<?php echo $this->htmlEscape($product->getName()) ?>"
					   href="<?php echo $product->getProductUrl() ?>">
						<img
							src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize($thumbWidth, $thumbHeight)->setWatermarkSize('30x10'); ?>"
							alt="<?php echo $this->htmlEscape($product->getName()) ?>"/>
					</a>
					<?php if (isset($labelType) && $showLabel): ?>
						<span class="<?php echo $labelType; ?>-label label"><?php echo $labelName; ?></span>
					<?php endif; ?>
				</p>

				<!-- Product Description -->
				<div class="product-information">
					<h5 class="product-name">
						<a title="<?php echo $this->htmlEscape($product->getName()) ?>"
						   href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName() ?></a>
					</h5>
					<?php echo $this->getReviewsSummaryHtml($product, true, true) ?>
					<?php echo $this->getPriceHtml($product, true, '_jmproduct_' . uniqid()); ?>
					<?php
					if (isset($maxChar)) :
						$productDesc = $product->getDescription();
						$productShortDesc = $product->getShortDescription();
						?>
						<p class="pdescription"><?php echo mb_substr(nl2br(strlen($productDesc) > 10 ? $productDesc : $productShortDesc), 0, $maxChar, 'UTF-8') . '...'; ?></p>
					<?php endif; ?>
					<!-- Add to cart -->
					<?php if ($product->isSaleable()): ?>
						<button class="button btn-cart"
								onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')">
							<span><?php echo $this->helper("catalog")->__('Add to Cart'); ?></span>
						</button>
					<?php else: ?>
						<div class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock'); ?></div>
					<?php endif; ?>
					<!-- Add to links -->
					<ul class="add-to-links">
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<li>
								<a href="<?php echo $this->helper('wishlist')->getAddUrl($product); ?>" class="link-wishlist">
									<?php echo $this->__('Wishlist'); ?>
								</a>
							</li>
						<?php endif; ?>
						<?php if ($compareUrl = $this->getAddToCompareUrl($product)): ?>
							<li>
								<a href="<?php echo $compareUrl ?>" class="link-compare"><?php echo $this->__('Compare'); ?></a>
							</li>
						<?php endif; ?>
					</ul>
				</div>
				<!-- /Product information -->
			</div>
		</li>
	<?php endforeach; ?>
<?php else: ?>
	<p class="note-msg"><?php echo $this->__("That's all we have for now.") ?></p>
<?php endif; ?>